# Generated by Django 4.2.6 on 2023-10-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Groceries', 'Groceries'), ('Restaurants', 'Restaurants'), ('Transport', 'Transport'), ('Cash', 'Cash'), ('Travel', 'Travel'), ('Health', 'Health'), ('Transfers', 'Transfers'), ('Other', 'Other'), ('Income', 'Income')], default='Other', max_length=20),
        ),
    ]
