# Generated by Django 4.2.6 on 2023-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_date_of_birth_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
