# Generated by Django 4.2.6 on 2023-10-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_account_amount_alter_income_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='base.customer'),
        ),
    ]
