# Generated by Django 4.2.6 on 2023-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_account_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Family', 'Family')], max_length=20),
        ),
    ]
